### ISSUE TITLE
The game goes not work well on Microsoft Edge

### ISSUE THREAD

**Issue by grondilu** [enkimute/ganja.js#2]
It works fine on chrome, though.

I know it's not a big deal but hey it's worth telling.

Great project, BTW! 🥇

If you have time, consider my own experiments with GA : [Clifford (Perl 6)](https://github.com/grondilu/clifford) and most recently [Clifford.js (javascript)](https://github.com/grondilu/clifford.js).

It's not as advanced as yours, but there may be ideas you could use, like how I used a modified version of the PEGJS javascript example grammar to parse the input.

**Comment by enkimute** [comment]
Thanks grondilu - sigh browser compatibility ;)

(wasn't finding a dom reference in edge using querySelector it turned out ..) 

I've taken a look at your Clifford.js and will send you some feedback via email - our implementations couldn't be more different so it'll be fun discussing those design choices a bit :). I did consider PEGJS, but in the end decided its scope is far beyond what I needed, and it wasn't worth dragging in an external dependency for what is now about 20 lines of code.  (I also wanted an inline syntax that parses as normal JS, meaning I know its valid when it enters ganja's translator and have no need for syntax checking and error reporting).
